# Generated by Django 4.2.2 on 2023-06-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descripion',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(choices=[('ALL', 'ALL'), ('Kids', 'Kids')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age_limit',
            field=models.CharField(choices=[('ALL', 'ALL'), ('Kids', 'Kids')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
